# -*- coding: utf-8 -*-
"""emtech py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zZCf4-ivX7seAK9l44R7DR8hrur1hfe
"""

import streamlit as st
from tensorflow.keras.models import load_model
from PIL import Image
import numpy as np

# Load model
model = load_model("cnn_model.h5")

# Title
st.title("🐱🐶 Cat vs Dog Classifier")

# Upload image
uploaded_file = st.file_uploader("Upload an image of a cat or dog", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    img = Image.open(uploaded_file).resize((64, 64)).convert("RGB")
    st.image(img, caption="Uploaded Image", use_column_width=True)

    img_array = np.array(img) / 255.0
    img_array = img_array.reshape(1, 64, 64, 3)

    prediction = model.predict(img_array)
    class_index = np.argmax(prediction)

    label = "Dog" if class_index == 1 else "Cat"
    st.write(f"Prediction: **{label}**")